//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int ID_journal { get; set; }
        public Nullable<int> ID_student { get; set; }
        public Nullable<int> ID_load { get; set; }
        public Nullable<System.DateTime> mark_date { get; set; }
        public Nullable<int> mark_value { get; set; }
    
        public virtual Load Load { get; set; }
        public virtual Student Student { get; set; }
    }
}
