//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Load()
        {
            this.Journal = new HashSet<Journal>();
            this.Timetable = new HashSet<Timetable>();
        }
    
        public int ID_load { get; set; }
        public Nullable<int> ID_group { get; set; }
        public Nullable<int> ID_distributed_dis { get; set; }
        public Nullable<int> sem1_weeks { get; set; }
        public Nullable<int> sem1_hours { get; set; }
        public Nullable<int> sem1_exam_num { get; set; }
        public Nullable<int> sem1_ID_exam_type { get; set; }
        public Nullable<int> sem2_weeks { get; set; }
        public Nullable<int> sem2_hours { get; set; }
        public Nullable<int> sem2_exam_num { get; set; }
        public Nullable<int> sem2_exam_hours { get; set; }
        public Nullable<int> sem2_ID_exam_type { get; set; }
    
        public virtual DistributedDiscipline DistributedDiscipline { get; set; }
        public virtual ExamType ExamType { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timetable> Timetable { get; set; }
    }
}
