//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YurecDBEntities : DbContext
    {
        public YurecDBEntities()
            : base("name=YurecDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Day> Day { get; set; }
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<DistributedDiscipline> DistributedDiscipline { get; set; }
        public virtual DbSet<ExamType> ExamType { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<Load> Load { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
    }
}
