//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int ID_timetable { get; set; }
        public Nullable<int> ID_load { get; set; }
        public Nullable<int> ID_day { get; set; }
        public Nullable<int> ID_position { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Load Load { get; set; }
        public virtual Position Position { get; set; }
    }
}
